### ISSUE TITLE
Исправить формирование JSON

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#21]
При попытке получить, например, данные пользователя, получаем невалидный JSON:
`{"status":"success","messages":["{"_issues":[{"userID":6,"firstName":"Mykhailo","lastName":"Borintsev","login":"**********","password":"**********"}]}"]}`
Кроме того, в ответе фигурирует **_issues**, что, скорее всего, не правильно.

**Comment by leader228228** [comment]
https://github.com/leader228228/bugtracker/issues/21

**Comment by leader228228** [comment]
https://github.com/leader228228/bugtracker/commit/6b09b6f5e7f03a19677ed0761a79d7ecd5414387
