### ISSUE TITLE
Добавить аннотации

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#22]
Необходимо добавить аннотации `@Autowired` там, где это нужно.

**Comment by leader228228** [comment]
@anry-das , других потенциальных мест, кроме конструкторов, куда можно добавить эту аннотацию, я не нашёл
Javadoc of @Autowired annotation says: "_If a class only declares a single constructor to begin with, it will always be used, even if not annotated_"
@anry-das , подскажи пожалуйста, все ли я учел?

**Comment by anry-das** [comment]
Можно и без аннотации, но я бы добавил **final** к полям

**Comment by leader228228** [comment]
https://github.com/leader228228/bugtracker/commit/b8c983b8690bab788ac3d65f4733962691f40e3a
