### ISSUE TITLE
getIssuesByAssignees должен возвращать один результат

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#25]
getIssuesByAssignees должен возвращать один результат согласно структуры БД

**Comment by leader228228** [comment]
@anry-das , здравствуй
Не совсем понял замечание, не мог ли бы ты уточнить почему именно этот метод должен возвращать одну issue?
Сейчас IssueServiceImpl#getIssuesByAssignees возвращает коллекцию issues, которые были назначены assigneesIDs (bt_users.user_id) для выполнения.
Т.е, в случае, когда таблица nc_users хранит информацию о пользователях:
- user_id = 1
- user_id = 2
- user_id = 3
, а bt_issues имеет записи о:
{issue_id = 10, assignee_id = 1}
{issue_id = 11, assignee_id = 1}
{issue_id = 20, assignee_id = 2}
{issue_id = 30, assignee_id = 3}
, то вызов IssueServiceImpl#getIssuesByAssignees(1,2) вернет информацию о issues с issue_id = 10, 11, 20

**Comment by anry-das** [comment]
Все правильно
Тикет закрываю.
