### ISSUE TITLE
Добавить автогенерацию ID

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#26]
При добавлении сущностей ID должны генериться автоматически. Передавать в запросе их не нужно.

**Comment by anry-das** [comment]
И, кстати, в сообщении 

> "The issue id = 0 was successfully updated (if it existed)"
`(if it existed)` нужно бы убрать

**Comment by anry-das** [comment]
А если такого ID нет, то нужно выводить об этом сообщение

**Comment by leader228228** [comment]
https://github.com/leader228228/bugtracker/commit/03b0679895c5f1b3229db686b2c7fd56da81b726
