### ISSUE TITLE
Поведение при изменении/добавлении

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#27]
При изменении/добавлении сущностей необходимо возвращать эти сущности.

Это еще один довод за то, чтобы отказаться от статусного сообщения в ответе.
Статус лучше передавать в заголовке.

**Comment by leader228228** [comment]
https://github.com/leader228228/bugtracker/commit/8022ebd0caeccd4ff8972039641859bcb7e31e3e
