### ISSUE TITLE
[COMMON] Замена getBean()

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#4]
В проекте необходимо заменить
`getBean()`
на **dependency injection**
Т.к. тут https://www.baeldung.com/spring-getbean сказано, что это не Spring way:

> **we don't want to use the getBean() method directly in our program.**

> Beans should be managed by the container. If we want to use one of them, we should rely on dependency injection rather than a direct call to ApplicationContext.getBean(). That way, we can avoid mixing application logic with framework-related details.

**Comment by leader228228** [comment]
Заменено в https://github.com/leader228228/bugtracker/commit/00c206691fcb518f32954d6c41204afa4a534724
