### ISSUE TITLE
[CONTROLLER] Заменить String в getPreparedStatementFor

### ISSUE THREAD

**Issue by anry-das** [leader228228/bugtracker#5]
В SearchIssuesController.getPreparedStatementFor() формируется довольно большая строка с запросом.
Предлагаю в нем заменить String на StringBuffer / StringBuilder

**Comment by anry-das** [comment]
И сразу вопрос:
зачем там же используется **logger.fatal();**? Может достаточно logger.debug();?

**Comment by leader228228** [comment]
Fixed at 88d28cb
